language: go

go:
- 1.13.x

script:
  - go get -v .
  - mkdir release
  - go build -o release/restic_wrapper-${TRAVIS_TAG}-linux-amd64

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  keep_history: true
  file_glob: true
  file: release/*
  on:
    tags: true
